engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/CommentIndentation:
        enabled: false
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- test/
