AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 150

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: fasle
